apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secrets
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongoDb.rootUser | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongoDb.rootPassword | b64enc }}
