version: '3'
services:
  chartmuseum:
    image: chartmuseum/chartmuseum
    ports:
      - '8081:8080'
    volumes:
    - chartmuseum_data:/charts
    environment:
        DEBUG: 1       
        STORAGE: local 
        STORAGE_LOCAL_ROOTDIR: /charts
volumes:
  chartmuseum_data:    